### ISSUE TITLE
Doesn't work on versions before 1.20.1 as it requires FML 47

### ISSUE THREAD

**Issue by EmiBondo** [MadaHaz/SleepingServerStopperMod-Forge#1]
Trying to run this on my 1.19.2 Server just leaves this error:

> [main/ERROR] [ne.mi.fm.lo.LanguageLoadingProvider/LOADING]: Missing language javafml version [47,) wanted by sleepingserverstoppermod-2.0.0-1.20.1.jar, found 43

**Comment by MadaHaz** [comment]
Think the error is popping up cause I used a higher version of forge to code it in, I rewrote it for the latest release of Forge 1.19. I've uploaded the file under v2.0.0 in the [release tab](https://github.com/MadaHaz/SleepingServerStopperMod-Forge/releases/tag/v2.0.0). Just make sure you download the 1.19 version.

⚠**NOTE**
I haven't gotten around to testing this version of the mod on a forge 1.19+ server. If there are any more issues let me know but it should work with how simple it is.

Let me know if it works 👍.
