### ISSUE TITLE
Server Does Not Close Right After Launch

### ISSUE THREAD

**Issue by AdriPlaysz** [MadaHaz/SleepingServerStopperMod-Forge#2]
The server just never closes After Server-Launch It only closes after somebody has joined and left the game.
Even when I set the "Should the Server close after Launch?"-option to "true" or "false".
I tested both "true" and "false" (with Minutes set to "3"), but It still ONLY closes after someone has joined and left...

**Comment by MadaHaz** [comment]
Yeah it was an issue with how I was reading the files, dumb mistake lol.
The new version (v3.0.0) works properly.
