### ISSUE TITLE
Support for Forge 1.16.5

### ISSUE THREAD

**Issue by OneWeekNotice** [MadaHaz/SleepingServerStopperMod-Forge#4]
Hello,

Thank you forking the Sleeping Server Stopper. 

I was wondering if this would work or can be added to support Forge 1.16.5.

Side question: How would one install this? Do I make a plugin folder or add it to the mod folder? Unsure if Forge has the concept of plugins.

Thanks!

**Comment by MadaHaz** [comment]
I might take a while since I'm a bit busy atm but I can try porting it over.

For Forge servers you place their mods in the **"mods"** folder. It should appear when you first start the server and it finishes generating the world. If it doesn't you can just make the folder and place the jar file in it. It is pretty similar to how you would use plugins if I remember them correctly.

**Comment by OneWeekNotice** [comment]
Thank you very much. Any support for Forge 1.16.5 would be appreciated.

Let me know if you need any help with testing

**Comment by MadaHaz** [comment]
@OneWeekNotice I managed to get something done, not sure if it works though. I haven't gotten around to testing it.

Can you try it out and see how it goes?
It should log the information in the CLI the server is opened. The format for the logs are, "[SSS] HEADER - MESSAGE". I'll list them below.

- [SSS] Server Empty - Server will shutdown in %d minute(s)!
- [SSS] Player joined - Server shutdown cancelled.
- [SSS] Server empty - Server shutting down.
- [SSS] Abort shutdown - %d connected player(s).

The %d is just a placeholder for a value. There should be a config file generated as well which you should be able to edit.

I'll release the file under a Beta tag in the releases section.

**Comment by OneWeekNotice** [comment]
@MadaHaz Thanks for the quick turn around time! Did some initial testing and everything is working as expected. This works perfectly with [mcsleepingserverstarter](https://github.com/vincss/mcsleepingserverstarter). Will post results below. 

Closing this ticket/ enhancement. Let me know if you need additional testing.

# Results

Note: this was tested with [mcsleepingserverstarter](https://github.com/vincss/mcsleepingserverstarter). Both worked perfectly together

File was generated in `<minecraft_folder>/config/sleepingserverstoppermod-common.toml`
```
["Configs for Sleeping Server Stopper Mod"]
        #How many minutes until the server closes. (Minimum is 1 minute!)
        Minutes = 2
        #Should the server shutdown on launch?
        ShutdownOnLaunch = true
```

## Logs

` [net.madahaz.sleepingserverstoppermod.SleepingServerStopperMod/]: [SSS] Server Empty - Server will shutdown in 2 minute(s)!`
` [net.madahaz.sleepingserverstoppermod.SleepingServerStopperMod/]: [SSS] Server empty - Server shutting down.`

`[net.madahaz.sleepingserverstoppermod.SleepingServerStopperMod/]: [SSS] Player joined - Server shutdown cancelled.`

Note: the only log I couldn't reproduce was `[SSS] Abort shutdown - %d connected player(s).`

**Comment by MadaHaz** [comment]
@OneWeekNotice Thanks for the thorough testing! The last message is for when multiple people are connected and one person leaves the server. So if the mod functions properly and the other messages are correctly outputted then there is no issue.

I'll move it out of the experimental release and put your name under the Contributes section for testers, thanks again. 👍
