### ISSUE TITLE
Can't find config file

### ISSUE THREAD

**Issue by KenaiiDev** [MadaHaz/SleepingServerStopperMod-Forge#5]
Where is the configuration file located? I've looked for it and can't find it

**Comment by MadaHaz** [comment]
It should be in a folder called `config` in the base directory of the server. The config file is called `sleepingserverstoppermod-common.toml`.

If you still can't find it then tell me what release you've downloaded.

**Comment by KenaiiDev** [comment]
I am using version "sleepingserverstoppermod-3.0.0-1.20.1". The configuration file has not been generated but I created it manually and it works.
